name: Build Grasshopper Plugin

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore the application
        run: msbuild /t:Restore /p:Configuration=Release
       
      - name: Build the application
        run: msbuild $env:Solution_Name /p:Configuration=Release
       