name: Build Grasshopper Plugin

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore the application
        run: msbuild /t:Restore /p:Configuration=Release
       
      - name: Build the application
        run: msbuild /p:Configuration=Release
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Run Test
        run: dotnet test .\GrasshopperCISampleTests\bin\Debug\GrasshopperCISampleTests.dll

      - name: Upload release build of plugin as artefact
        uses: actions/upload-artifact@v2
        with:
          name: GrasshopperComponent
          path: ./GrasshopperCISample/bin/GrasshopperCISample.gha